# List of jobs to run sequentially
jobs:
  - name_prefix: "ft_n10_t0.60" # Unique name for this experiment run
    model_path: "/home/users/ntu/chong032/scratch/r1-distill"
    server:
      tensor_parallel_size: 2
      hours: 8
      enable_reasoning: true
      reasoning_parser: "deepseek_r1"
    client:
      hours: 8
      gpus: 1
      initial_delay_minutes: 10
    eval:
      type: "similarity"
      n_start: 10
      threshold: 0.60
      pruning_strategy: "fewest_thoughts"
      model_name: "R1-Distill-Qwen-14B" # Unique name for outputs
      model_identifier: "/home/users/ntu/chong032/scratch/r1-distill"
      tokenizer_path: "/home/users/ntu/chong032/scratch/r1-distill"
      dataset_name: "gpqa_diamond"
      num_qns: 100

  # - name_prefix: "ft_n10_t0.72" # Unique name for this experiment run
  #   model_path: "/home/users/ntu/chong032/scratch/r1-distill"
  #   server:
  #     tensor_parallel_size: 2
  #     hours: 8
  #     enable_reasoning: true
  #     reasoning_parser: "deepseek_r1"
  #   client:
  #     hours: 8
  #     gpus: 1
  #     initial_delay_minutes: 10
  #   eval:
  #     type: "similarity"
  #     n_start: 10
  #     threshold: 0.72
  #     pruning_strategy: "fewest_thoughts"
  #     model_name: "R1-Distill-Qwen-14B" # Unique name for outputs
  #     model_identifier: "/home/users/ntu/chong032/scratch/r1-distill"
  #     tokenizer_path: "/home/users/ntu/chong032/scratch/r1-distill"
  #     dataset_name: "gpqa_diamond"
  #     num_qns: 100

  - name_prefix: "ft_n10_t0.90" # Unique name for this experiment run
    model_path: "/home/users/ntu/chong032/scratch/r1-distill"
    server:
      tensor_parallel_size: 2
      hours: 8
      enable_reasoning: true
      reasoning_parser: "deepseek_r1"
    client:
      hours: 8
      gpus: 1
      initial_delay_minutes: 10
    eval:
      type: "similarity"
      n_start: 10
      threshold: 0.90
      pruning_strategy: "fewest_thoughts"
      model_name: "R1-Distill-Qwen-14B" # Unique name for outputs
      model_identifier: "/home/users/ntu/chong032/scratch/r1-distill"
      tokenizer_path: "/home/users/ntu/chong032/scratch/r1-distill"
      dataset_name: "gpqa_diamond"
      num_qns: 100

  # - name_prefix: "sc_n5"
  #   model_path: "/home/users/ntu/chong032/scratch/r1-distill"
  #   server:
  #     tensor_parallel_size: 2
  #     hours: 8
  #     enable_reasoning: true
  #     reasoning_parser: "deepseek_r1"
  #   client:
  #     hours: 8
  #     initial_delay_minutes: 10
  #     # gpus: 0 # GPUs ignored for sc_control, but can be explicit
  #   eval:
  #     type: "sc_control" # Must match subparser name
  #     n_start: 5 # Number of chains for SC
  #     model_name: "R1-Distill-Qwen-14B"
  #     model_identifier: "/home/users/ntu/chong032/scratch/r1-distill"
  #     tokenizer_path: "/home/users/ntu/chong032/scratch/r1-distill"
  #     dataset_name: "gpqa_diamond"
  #     start: 1 # Example using start/end instead of num_qns
  #     end: 3